### ISSUE TITLE
setup google calendar feed for group tour dates

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/tro-peaks#22]
* create a new gmail account for tro-peaks
* use this gmail to setup a google calendar and
add dates from May to Dec 2019
http://www.tro-peaks.com/climbdates.html
* update the home page and the /calendar page to use this google calendar feed (it currently is using college lutheran calandar feed)
* provide the login and password for this gmail account back to Josh is a private message (we will have Tom change it later when his site goes to production status)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves don't forget to message me the gmail address and password, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman this events are now fully updated in the google calendar
