### ISSUE TITLE
Fix issue when clicking side menu does not display the page at top of page, which occurs after clicking an interior nav that scrollsIntoView

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/tro-peaks#61]

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I'm not sure what you mean by this issue. could you please provide some more context?

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves click the **Safari** link in the side menu, then click the **Culture** interior page link, then click the **Staff** side menu, and notice that it does not scroll back to the top of the page. This problem occurs on every page after a scrollIntoView has been used.
